### ISSUE TITLE
How can I enter password just one time for run several commands?  (Question)

### ISSUE THREAD

**Issue by joseluisq** [neoziro/ssh-pool#14]
Actually for each command exec I should repeat the password.
Is it possible to enter password just one time on terminal for several commands?

Regards.

**Comment by gregberge** [comment]
You can pute your ssh key on servers https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2.

**Comment by joseluisq** [comment]
@neoziro I appreciate your help.
For now I solved this requesting for user input stdin on terminal with [node read](https://github.com/isaacs/read).
Thanks
