### ISSUE TITLE
Shell substitution

### ISSUE THREAD

**Issue by peterkuma** [neoziro/ssh-pool#16]
Hi,

ssh-pool uses `child_process.exec` for running an ssh command, and I think it does not handle all character substitution correctly, e.g:

```
const sshPool = require('ssh-pool');
const pool = new sshPool.ConnectionPool(['localhost']);
pool.run('X=1; echo $X').then(res => {
  console.log(res[0].stdout);
});
```

will print a blank line, while `1` would be expected. This is because $X is substituted from the local shell. Also on Windows shell is executed with `cmd.exe` where substitution rules are different (e.g. commands containing new lines do not work).

Replacing `exec` with `execFile` (which accepts an array of arguments) in `connection.js` seems to work fine on Linux and Windows, but I am not sure if it does not have any unforeseen consequences. 

A preliminary pull request #17 contains the modifications, but apparently many tests would need to be updated too.

**Comment by trkoch** [comment]
Came across this issue as well. Is there a workaround? I'd like to read the current user uid and pass it along to another command. The only way I can think of is executing multiple commands and remembering the value within the script context. That, however, seems cumbersome. Concerning your pull request, a more conservative approach perhaps would be to add a separate method.
