### ISSUE TITLE
copyViaScp cause I/O error with parallel copying

### ISSUE THREAD

**Issue by qiyuan-wang** [neoziro/ssh-pool#22]
how to reproduce:
  1. set a environment no rsync installed;
  2. make a ConnectionPool with 2 remotes at least;
  3. try copy a folder to remotes' destination.

result:
  there should be a fatal error about **{foldername}.tmp.tar.gz**, 'can not found' or 'can not remove' etc.

reason:
  `copyViaScp` generates tmp.tar file with same folder name. With parallel copying, first call removed the temp file after uploading it to dest, which caused other fail to get the file.

solution:
  generates tmp.tar file name with a unique id for each call of `copyViaScp`.

**Comment by neoziro** [comment]
@qiyuan-wang shipit is going to change and to be actively maintained. This issue is old, so I closed it. Feel free to open a new one if you still experienced a problem.

**Comment by gregberge** [comment]
@qiyuan-wang will be fixed in https://github.com/shipitjs/ssh-pool/pull/26
