### ISSUE TITLE
is this still being maintained?

### ISSUE THREAD

**Issue by gmaliar** [neoziro/ssh-pool#23]

**Comment by timkelty** [comment]
I apologize.
It is, but I'm afraid quite sporadically at the moment.

I assume you're looking to get your PR merged?

**Comment by gmaliar** [comment]
or help you maintain this repo even, if you'd like ...

**Comment by gmaliar** [comment]
@timkelty thoughts?

**Comment by timkelty** [comment]
I've talked with @neoziro and we have some plans for getting Shipit 2.x launched and more actively maintained.

We will definitely keep you in mind as a maintainer as we make a roadmap.
