### ISSUE TITLE
It would be nice to see the `remote.copy`percentage of achievement

### ISSUE THREAD

**Issue by welcoMattic** [neoziro/ssh-pool#5]
For heavy repository, would be cool to know the progress of the transfer, like

`[46%] 92Mo / 200Mo`

Live updated ;)

**Comment by timkelty** [comment]
Once https://github.com/shipitjs/shipit/pull/28 is merged, you can pass `--info=progress2` to `remote.copy`.
Up to @neoziro if he wants that to be a default or not.

I made PR for it to be the default for Shipit's use of `remote.copy`: https://github.com/shipitjs/shipit/pull/28
