### ISSUE TITLE
Impossible to execute any `git`or `ssh` command on remote

### ISSUE THREAD

**Issue by welcoMattic** [neoziro/ssh-pool#6]
I'm trying to execute a `git clone` command on a remote server, the result is :

``` bash
Permission denied (publickey).
```

However, my key is valid. I can execute `git clone` when I'm connected through SSH on my Terminal.

Any idea ? Is it a bug, or is it block by default ?

**Comment by gregberge** [comment]
Try running the command without being connected. running command in SSH and be connected is two different things that you can't compare.

I think it's a problem of user environment on the server that differs when you are logged in or not.
